version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mv-unisolve-be
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/app_start.sh
      timeout: 300
      runas: ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
